//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrique.Utils.X7Actions
{
    
    
    /// <summary>
    /// The ConfigurationSection1 Configuration Section.
    /// </summary>
    public partial class ConfigurationSection1 : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the ConfigurationSection1 Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string ConfigurationSection1SectionName = "configurationSection1";
        
        /// <summary>
        /// Gets the ConfigurationSection1 instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public static global::Andrique.Utils.X7Actions.ConfigurationSection1 Instance
        {
            get
            {
                return ((global::Andrique.Utils.X7Actions.ConfigurationSection1)(global::System.Configuration.ConfigurationManager.GetSection(global::Andrique.Utils.X7Actions.ConfigurationSection1.ConfigurationSection1SectionName)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Andrique.Utils.X7Actions.ConfigurationSection1.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::Andrique.Utils.X7Actions.ConfigurationSection1.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region AttributeProperty1 Property
        /// <summary>
        /// The XML name of the <see cref="AttributeProperty1"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string AttributeProperty1PropertyName = "attributeProperty1";
        
        /// <summary>
        /// Gets or sets the AttributeProperty1.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The AttributeProperty1.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Andrique.Utils.X7Actions.ConfigurationSection1.AttributeProperty1PropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public int AttributeProperty1
        {
            get
            {
                return ((int)(base[global::Andrique.Utils.X7Actions.ConfigurationSection1.AttributeProperty1PropertyName]));
            }
            set
            {
                base[global::Andrique.Utils.X7Actions.ConfigurationSection1.AttributeProperty1PropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Andrique.Utils.X7Actions
{
    
    
    /// <summary>
    /// The ConfigurationElement1 Configuration Element.
    /// </summary>
    public partial class ConfigurationElement1 : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region AttributeProperty1 Property
        /// <summary>
        /// The XML name of the <see cref="AttributeProperty1"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string AttributeProperty1PropertyName = "attributeProperty1";
        
        /// <summary>
        /// Gets or sets the AttributeProperty1.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The AttributeProperty1.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Andrique.Utils.X7Actions.ConfigurationElement1.AttributeProperty1PropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public bool AttributeProperty1
        {
            get
            {
                return ((bool)(base[global::Andrique.Utils.X7Actions.ConfigurationElement1.AttributeProperty1PropertyName]));
            }
            set
            {
                base[global::Andrique.Utils.X7Actions.ConfigurationElement1.AttributeProperty1PropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Andrique.Utils.X7Actions
{
    
    
    /// <summary>
    /// A collection of ConfigurationElement1 instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::Andrique.Utils.X7Actions.ConfigurationElement1), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::Andrique.Utils.X7Actions.ConfigurationElementCollection1.ConfigurationElement1PropertyName)]
    public partial class ConfigurationElementCollection1 : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::Andrique.Utils.X7Actions.ConfigurationElement1"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string ConfigurationElement1PropertyName = "configurationElement1";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override string ElementName
        {
            get
            {
                return global::Andrique.Utils.X7Actions.ConfigurationElementCollection1.ConfigurationElement1PropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::Andrique.Utils.X7Actions.ConfigurationElementCollection1.ConfigurationElement1PropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::Andrique.Utils.X7Actions.ConfigurationElement1)(element)).AttributeProperty1;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::Andrique.Utils.X7Actions.ConfigurationElement1"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::Andrique.Utils.X7Actions.ConfigurationElement1"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::Andrique.Utils.X7Actions.ConfigurationElement1();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::Andrique.Utils.X7Actions.ConfigurationElement1"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Andrique.Utils.X7Actions.ConfigurationElement1"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::Andrique.Utils.X7Actions.ConfigurationElement1 this[int index]
        {
            get
            {
                return ((global::Andrique.Utils.X7Actions.ConfigurationElement1)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::Andrique.Utils.X7Actions.ConfigurationElement1"/> with the specified key.
        /// </summary>
        /// <param name="attributeProperty1">The key of the <see cref="global::Andrique.Utils.X7Actions.ConfigurationElement1"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::Andrique.Utils.X7Actions.ConfigurationElement1 this[object attributeProperty1]
        {
            get
            {
                return ((global::Andrique.Utils.X7Actions.ConfigurationElement1)(base.BaseGet(attributeProperty1)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::Andrique.Utils.X7Actions.ConfigurationElement1"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="configurationElement1">The <see cref="global::Andrique.Utils.X7Actions.ConfigurationElement1"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public void Add(global::Andrique.Utils.X7Actions.ConfigurationElement1 configurationElement1)
        {
            base.BaseAdd(configurationElement1);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::Andrique.Utils.X7Actions.ConfigurationElement1"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="configurationElement1">The <see cref="global::Andrique.Utils.X7Actions.ConfigurationElement1"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public void Remove(global::Andrique.Utils.X7Actions.ConfigurationElement1 configurationElement1)
        {
            base.BaseRemove(this.GetElementKey(configurationElement1));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::Andrique.Utils.X7Actions.ConfigurationElement1"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Andrique.Utils.X7Actions.ConfigurationElement1"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::Andrique.Utils.X7Actions.ConfigurationElement1 GetItemAt(int index)
        {
            return ((global::Andrique.Utils.X7Actions.ConfigurationElement1)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::Andrique.Utils.X7Actions.ConfigurationElement1"/> with the specified key.
        /// </summary>
        /// <param name="attributeProperty1">The key of the <see cref="global::Andrique.Utils.X7Actions.ConfigurationElement1"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::Andrique.Utils.X7Actions.ConfigurationElement1 GetItemByKey(bool attributeProperty1)
        {
            return ((global::Andrique.Utils.X7Actions.ConfigurationElement1)(base.BaseGet(((object)(attributeProperty1)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
